#!/usr/bin/env bash
set -euo pipefail

RUN_DIR="${1:?Usage: synthesize-audit.sh <RUN_DIR>}"
source "$RUN_DIR/setup/env.sh"

AUDIT_DATE=$(date +%Y-%m-%d)
REPORT_FILE="$SDK_DIR/docs/sdk-audit-${AUDIT_DATE}.md"
mkdir -p "$SDK_DIR/docs"

CRITICAL=0
MAJOR=0
MINOR=0
INFO=0
RETRACTED=0

count_severities() {
  local file="$1"
  [[ ! -f "$file" ]] && return

  local in_retracted_block="false"
  local current_severity=""

  while IFS= read -r line; do
    if [[ "$line" =~ ^###[[:space:]]+FINDING: ]]; then
      if [[ -n "$current_severity" && "$in_retracted_block" == "false" ]]; then
        case "$current_severity" in
          critical) CRITICAL=$((CRITICAL + 1)) ;;
          major)    MAJOR=$((MAJOR + 1)) ;;
          minor)    MINOR=$((MINOR + 1)) ;;
          info)     INFO=$((INFO + 1)) ;;
        esac
      elif [[ "$in_retracted_block" == "true" ]]; then
        RETRACTED=$((RETRACTED + 1))
      fi
      current_severity=""
      in_retracted_block="false"
    fi

    if echo "$line" | grep -qi '^- SEVERITY:'; then
      current_severity=$(echo "$line" | sed 's/.*SEVERITY:[[:space:]]*//' | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]')
    fi
    if echo "$line" | grep -qi '^- STATUS:[[:space:]]*retracted'; then
      in_retracted_block="true"
    fi
  done < "$file"

  if [[ -n "$current_severity" && "$in_retracted_block" == "false" ]]; then
    case "$current_severity" in
      critical) CRITICAL=$((CRITICAL + 1)) ;;
      major)    MAJOR=$((MAJOR + 1)) ;;
      minor)    MINOR=$((MINOR + 1)) ;;
      info)     INFO=$((INFO + 1)) ;;
    esac
  elif [[ "$in_retracted_block" == "true" ]]; then
    RETRACTED=$((RETRACTED + 1))
  fi
}

for f in "$RUN_DIR"/domain-*-findings.md; do
  count_severities "$f"
done
for f in "$RUN_DIR"/xcut-*-findings.md; do
  count_severities "$f"
done
for f in "$RUN_DIR"/regression-*-findings.md; do
  count_severities "$f"
done

VERDICT="PASS"
if [[ "$CRITICAL" -ge 1 ]]; then
  VERDICT="FAIL"
elif [[ "$MAJOR" -ge 1 ]]; then
  VERDICT="PASS WITH ISSUES"
fi

SDK_VERSION=$(PKG_PATH="$SDK_DIR/package.json" node -e "console.log(require(process.env.PKG_PATH).version)" 2>/dev/null || echo "unknown")
NODE_VERSION=$(cat "$RUN_DIR/setup/node-version.txt" 2>/dev/null || echo "unknown")

cat > "$REPORT_FILE" <<HEADER
# SDK Functional Audit Report

**Date:** ${AUDIT_DATE}
**SDK Version:** ${SDK_VERSION}
**Node.js:** ${NODE_VERSION}
**Run Directory:** ${RUN_DIR}

## Verdict: ${VERDICT}

| Severity | Count |
|----------|-------|
| Critical | ${CRITICAL} |
| Major | ${MAJOR} |
| Minor | ${MINOR} |
| Info | ${INFO} |
| Retracted | ${RETRACTED} |

---

HEADER

echo "## Wave 1 — Domain Agent Findings" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

for domain in metering config resilience crosscutting; do
  FFILE="$RUN_DIR/domain-${domain}-findings.md"
  if [[ -f "$FFILE" ]]; then
    cat "$FFILE" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "---" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
  else
    echo "### ${domain} domain — N/A (agent did not complete)" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
  fi
done

echo "## Wave 2 — Cross-cutting Script Findings" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

for script in security-lint provider-drift; do
  FFILE="$RUN_DIR/xcut-${script}-findings.md"
  if [[ -f "$FFILE" ]]; then
    cat "$FFILE" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "---" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
  else
    echo "### ${script} — N/A (script did not complete)" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
  fi
done

echo "## Wave 3 — Regression Library Findings" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

REGRESSION_FILE="$RUN_DIR/regression-1-findings.md"
if [[ -f "$REGRESSION_FILE" ]]; then
  cat "$REGRESSION_FILE" >> "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"
else
  echo "Regression agent did not complete." >> "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"
fi

echo "---" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "## Recommendations" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

if [[ "$CRITICAL" -ge 1 ]]; then
  echo "- **CRITICAL findings require immediate attention** before any release." >> "$REPORT_FILE"
fi
if [[ "$MAJOR" -ge 1 ]]; then
  echo "- **Major findings should be addressed** before the next public release." >> "$REPORT_FILE"
fi
if [[ "$MINOR" -ge 1 ]]; then
  echo "- Minor findings can be addressed in a follow-up PR." >> "$REPORT_FILE"
fi
if [[ "$CRITICAL" -eq 0 && "$MAJOR" -eq 0 && "$MINOR" -eq 0 ]]; then
  echo "- No actionable findings. SDK is in good shape." >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "Generated by sdk-functional-audit orchestrator." >> "$REPORT_FILE"

echo "Synthesis complete: $REPORT_FILE" >&2
echo "Verdict: $VERDICT (critical=$CRITICAL, major=$MAJOR, minor=$MINOR, info=$INFO, retracted=$RETRACTED)" >&2
