export const DEFAULT_REVENIUM_BASE_URL = "https://api.revenium.ai";

export const CIRCUIT_BREAKER_CONFIG = {
  FAILURE_THRESHOLD: 5,
  RECOVERY_TIMEOUT: 30000,
  SUCCESS_THRESHOLD: 3,
  TIME_WINDOW: 60000,
  MAX_FAILURE_HISTORY_SIZE: 1000,
  CLEANUP_INTERVAL: 300000,
  CLEANUP_SIZE_THRESHOLD: 100,
} as const;

export const RETRY_CONFIG = {
  BASE_DELAY: 1000,
  MAX_DELAY: 5000,
  JITTER_FACTOR: 0.1,
} as const;

export const DEFAULT_CONFIG = {
  API_TIMEOUT: 5000,
  MAX_RETRIES: 3,
  FAIL_SILENT: true,
  CAPTURE_PROMPTS: false,
  MAX_PROMPT_SIZE: 50000,
} as const;

export const MESSAGE_PATTERNS_TYPE_NETWORK = ["network", "timeout", "ECONNRESET"];

export const ERROR_MESSAGE_PATTERNS_TYPE_CONFIG = ["config", "key", "unauthorized"];

export const ENV_VARS = {
  REVENIUM_API_KEY: "REVENIUM_METERING_API_KEY",
  REVENIUM_API_KEY_ALT: "REVENIUM_API_KEY",
  REVENIUM_BASE_URL: "REVENIUM_METERING_BASE_URL",
  REVENIUM_BASE_URL_ALT: "REVENIUM_BASE_URL",
  DEBUG: "REVENIUM_DEBUG",
  PRINT_SUMMARY: "REVENIUM_PRINT_SUMMARY",
  TEAM_ID: "REVENIUM_TEAM_ID",
  CAPTURE_PROMPTS: "REVENIUM_CAPTURE_PROMPTS",
  MAX_PROMPT_SIZE: "REVENIUM_MAX_PROMPT_SIZE",
} as const;

export const API_ENDPOINTS = {
  AI_COMPLETIONS: "/ai/completions",
  AI_IMAGES: "/ai/images",
  AI_AUDIO: "/ai/audio",
  AI_VIDEO: "/ai/video",
  TOOL_EVENTS: "/tool/events",
} as const;

export const SUMMARY_PRINTER_CONFIG = {
  MAX_RETRIES: 3,
  RETRY_DELAY: 2000,
  FETCH_TIMEOUT: 10000,
} as const;
